### ISSUE TITLE
Add Github Action

### ISSUE THREAD

**Issue by thanhhx-zinza** [thanhhx-zinza/training_social_network#22]
# TODO
- Run codesniffer
- Run unit test

**Comment by tungtt1006** [comment]
Issue này là set up dưới local thôi đúng ko ạ, chưa phải cấu hình trên git action đúng ko a

**Comment by thanhhx-zinza** [comment]
DONE

**Comment by thanhhx-zinza** [comment]
@tungtt1006 

Cải tiến Action cho nhanh hơn

![image](https://user-images.githubusercontent.com/26565145/154627094-9150dfd7-11c5-439f-a25d-16aca95576bc.png)
![image](https://user-images.githubusercontent.com/26565145/154627276-c2b362ad-3d5c-4191-bf63-e58c99977fa9.png)

Phần này chậm do init mysql
Tuy nhiên trong github action, nếu dùng image ubuntu của github thì trong đó có cài sẵn mysql rồi thì phải.
Tìm document của github liên quan đến những thứ đc cài sẵn của github để tận dụng lại luôn.


![image](https://user-images.githubusercontent.com/26565145/154627252-098e171c-88f4-4a63-ba40-d2e9b5b2b992.png)

Phần này lúc nào cũng phải download và install lại.
Tìm hiểu về cache của github action để tận dụng lại thư viện đã cài giữa các lần chạy.
